[package]
name = "celluloid-core"
version = "0.1.2"
edition = "2021"
description = "Recorder and file format for Celluloid animations"
license = "MIT"
homepage = "https://github.com/careyi3/celluloid"
repository = "https://github.com/careyi3/celluloid"
readme = "README.md"
keywords = ["animation", "visualization", "debugging", "advent-of-code", "grid"]
categories = ["visualization", "development-tools::debugging"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
