[workspace]
members = ["celluloid-core", "celluloid-view", "celluloid-web", "celluloid", "xtask"]
resolver = "2"

[workspace.dependencies]
celluloid-core = { path = "celluloid-core", version = "0.1.1" }
celluloid-view = { path = "celluloid-view", version = "0.1.1", default-features = false }
eframe = { version = "0.36", default-features = false, features = ["default_fonts"] }

[profile.wasm]
inherits = "release"
opt-level = "z"
strip = true
lto = true
codegen-units = 1
incremental = false
